//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %
        ///1	Ppron
        ///2	Ipron
        ///3	Article
        ///4	Prep
        ///5	Auxverb
        ///6	Adverb
        ///7	Conj
        ///8	Negate
        ///%
        ///a	3
        ///about	4	6
        ///above	4
        ///absolutely	6
        ///abt	4
        ///across	4
        ///actually	6
        ///after	4
        ///again	6
        ///against	4
        ///ahead	4
        ///aint	5	8
        ///ain&apos;t	5	8
        ///almost	6
        ///along	4
        ///already	6
        ///also	6	7
        ///altho	7
        ///although	7
        ///am	5
        ///amid	4
        ///amidst	4
        ///among*	4
        ///an	3
        ///and	7
        ///another	2
        ///anybod*	2
        ///anymore	2
        ///anyone*	2
        ///anything	2
        ///anyway*	6
        ///anywhere	6
        ///apparently	6
        ///are	5
        ///arent	5	8
        ///aren&apos;t	5	8
        ///around	4	6
        ///as	4	7
        ///at	4
        ///atop	4
        ///away	4
        ///awhile	6
        ///back	6
        ///barely	6
        ///ba [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LSM {
            get {
                return ResourceManager.GetString("LSM", resourceCulture);
            }
        }
    }
}
